const authenticate = (req, res, next ) => {
  try {

  } catch(err) {
    
  }
}